kind: pipeline
name: doh-server

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/doh-server
    username: ich777
    password:
      from_secret: docker_password
    tags: latest